# Generated by Django 4.1.7 on 2023-03-28 16:07

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_rename_time_film_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="country",
            field=django_countries.fields.CountryField(max_length=255),
        ),
    ]
