# Generated by Django 4.1.7 on 2023-03-30 14:20

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0003_alter_film_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="country",
            field=django_countries.fields.CountryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="film",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="film",
            name="duration",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="film",
            name="rating",
            field=models.FloatField(null=True),
        ),
    ]
