# Generated by Django 4.1.7 on 2023-03-31 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0004_alter_film_country_alter_film_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.IntegerField(unique=True)),
                (
                    "chat_name",
                    models.CharField(
                        default="Chat <django.db.models.fields.IntegerField>",
                        max_length=255,
                    ),
                ),
                ("spam", models.BooleanField()),
                (
                    "last_film_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="db.film",
                    ),
                ),
            ],
        ),
    ]
