# Generated by Django 4.1.7 on 2023-03-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0005_chat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="chat_id",
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="chat",
            name="chat_name",
            field=models.CharField(
                default="Chat <django.db.models.fields.BigIntegerField>", max_length=255
            ),
        ),
    ]
